stages:
  - install
  - build
  - publish

include:
  - project: devops/pipes
    file: /templates/node-build.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
    ref: main
