---
stages:
  - install
  - build
  - publish

variables:
  NODE_VERSION: 24-alpine
  NODE_PACKAGE_MANAGER: pnpm
  SKIP_SIMPLE_GIT_HOOKS: '1'

include:
  - project: devops/pipelines
    ref: node@2.0.0
    file:
      - /node/install.gitlab-ci.yml
      - /node/build.gitlab-ci.yml
      - /node/lint.gitlab-ci.yml

  - project: devops/pipelines
    ref: semantic-release@2.0.0
    file:
      - /semantic-release/publish.gitlab-ci.yml

install:
  stage: install
  extends:
    - .node-install
  rules:
    - when: on_success

lint:
  stage: build
  extends:
    - .node-lint
  rules:
    - when: on_success

build:
  stage: build
  extends:
    - .node-build
  needs:
    - install
  dependencies:
    - install
  rules:
    - when: on_success

semantic-release:
  stage: publish
  extends:
    - .semantic-release
  needs:
    - build
    - lint
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(master|main|alpha|beta|rc|next)$/'
      interruptible: true
    - when: never
