---
stages:
  - install
  - build
  - publish

variables:
  NODE_VERSION: 22-alpine
  SKIP_SIMPLE_GIT_HOOKS: '1'

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
