---
stages:
  - install
  - build
  - publish

variables:
  NODE_VERSION: 20-alpine

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
