---
stages:
  - install
  - build
  - publish

variables:
  NODE_VERSION: 24-alpine
  NODE_PACKAGE_MANAGER: pnpm
  SKIP_SIMPLE_GIT_HOOKS: '1'

include:
  - project: devops/pipelines
    ref: node@1.2.0
    file:
      - /node/install.gitlab-ci.yml
      - /node/build.gitlab-ci.yml
      - /node/lint.gitlab-ci.yml
    inputs:
      rules:
        - when: always

  - project: devops/pipelines
    ref: semantic-release@1.6.1
    file:
      - /semantic-release/publish.gitlab-ci.yml
    inputs:
      rules:
        - if: '$CI_COMMIT_REF_NAME =~ /^(master|main|alpha|beta|rc|next)$/'
          interruptible: true
        - when: never

install:
  stage: install
  extends:
    - .node-install

lint:
  stage: build
  extends:
    - .node-lint

build:
  stage: build
  extends:
    - .node-build
  needs:
    - install
  dependencies:
    - install

semantic-release:
  stage: publish
  extends:
    - .semantic-release
  needs:
    - build
    - lint
  dependencies:
    - build
