stages:
  - install
  - build
  - publish

variables:
  NODE_PACKAGE_MANAGER: pnpm
  NODE_LINT_COMMAND: lint

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
